#' @title coef method for objects of class \code{mtar}
#' @param object an object of class \code{mtar} generated by a call to the function \code{mtar()}.
#' @param FUN the function to be applied to the chains resulting from the MCMC-type algorithm for
#'            each model parameter. By default, \code{FUN} is set to \code{mean()}.
#' @param ... optional arguments to FUN.
#' @return a list composed of the values obtained from \code{FUN} when the latter is computed using
#'         chains resulting from the MCMC-type algorithm for each model parameter.
#' @method coef mtar
#' @export
coef.mtar <- function(object,...,FUN=mean){
  k <- ncol(object$data[[1]]$y)
  n.sim <- object$n.sim
  out_ <- list()
  for(i in 1:object$regim){
      out_[[i]] <- list()
      out <- outs <- vector()
      for(j in 1:k){
          temp <- object$chains[[i]]$location[,seq(j,n.sim*k,k)]
          temps <- matrix(matrix(object$chains[[i]]$scale,k,n.sim*k)[,seq(j,n.sim*k,k)],nrow=k)
          out <- cbind(out,apply(temp,1,FUN,...))
          outs <- cbind(outs,apply(temps,1,FUN,...))
      }
      if(object$ssvs){
         quien <- object$deterministic + seq(k,object$ars$p[i]*k,k)
         namezeta <- paste0("OS.lag(",1:object$ars$p[i],")")
         if(object$ars$q[i]>0){
            quien <- c(quien,max(quien)+seq(object$r,object$ars$q[i]*object$r,object$r))
            namezeta <- c(namezeta,paste0("ES.lag(",1:object$ars$q[i],")"))
         }
         if(object$ars$d[i]>0){
            quien <- c(quien,max(quien)+seq(1,object$ars$d[i],1))
            namezeta <- c(namezeta,paste0("TS.lag(",1:object$ars$d[i],")"))
         }
         temp <- matrix(apply(matrix(object$chains[[i]]$zeta[quien,],length(quien),n.sim),1,FUN,...),1,length(quien))
         colnames(temp) <- namezeta
         rownames(temp) <- "zeta"
         out_[[i]]$zeta <- temp
      }
      out_[[i]]$location <- out
      out_[[i]]$scale <- outs
      colnames(out_[[i]]$location) <- colnames(out_[[i]]$scale) <- rownames(out_[[i]]$scale) <- colnames(object$data[[1]]$y)
  }
  if(object$regim > 1){
     out_$delay <- apply(matrix(object$chains$h,1,n.sim),1,FUN,...)
     out_$thresholds <- matrix(apply(object$chains$thresholds,1,FUN,...),object$regim-1,1)
     rownames(out_$thresholds) <- paste0("Threshold",1:(object$regim-1))
     colnames(out_$thresholds) <- ""
  }
  if(object$dist %in% c("Skew-normal","Skew-Student-t")){
     out_$skewness <- matrix(apply(object$chains$delta,1,FUN,...),k,1)
     rownames(out_$skewness) <- paste0("delta",1:k)
     colnames(out_$skewness) <- ""
  }
  if(object$dist %in% c("Slash","Contaminated normal","Student-t","Hyperbolic","Skew-Student-t")){
     out_$extra <- matrix(apply(object$chains$extra,1,FUN,...),nrow(object$chains$extra),1)
     rownames(out_$extra) <- paste0("nu",1:nrow(object$chains$extra))
     colnames(out_$extra) <- ""
  }
  return(out_)
}

#' @title vcov method for objects of class \code{mtar}
#' @param object an object of class \code{mtar} generated by a call to the function \code{mtar()}.
#' @param FUN the function to be applied to the chains for the scale parameters resulting
#'            from the MCMC-type algorithm. By default, \code{FUN} is set to \code{mean()}.
#' @param ... optional arguments to FUN.
#' @return a list composed of the values obtained from \code{FUN} when the latter is computed using
#'         chains resulting from the MCMC-type algorithm for the scale parameters.
#' @method vcov mtar
#' @export
vcov.mtar <- function(object,...,FUN=mean){
  k <- ncol(object$data[[1]]$y)
  n.sim <- object$n.sim
  out_ <- list()
  for(i in 1:object$regim){
      outs <- vector()
      for(j in 1:k){
          temps <- matrix(matrix(object$chains[[i]]$scale,k,n.sim*k)[,seq(j,n.sim*k,k)],nrow=k)
          outs <- cbind(outs,apply(temps,1,FUN,...))
      }
      out_[[i]] <- outs
      colnames(out_[[i]]) <- rownames(out_[[i]]) <- colnames(object$data[[1]]$y)
  }
  return(out_)
}


#' @method summary mtar
#' @export
summary.mtar <- function(object, credible=0.95,...){
  k <- ncol(object$data[[1]]$y)
  n.sim <- object$n.sim
  out_ <- list()
  resumen <- function(x){
        x <- matrix(x,ifelse(is.null(nrow(x)),1,nrow(x)),ifelse(is.null(ncol(x)),length(x),ncol(x)))
        y <- matrix(0,nrow(x),4)
        y[,1] <- rowMeans(x)
        y[,2] <- apply(x,1,function(x) min(mean(sign(median(x))*x > 0),1-1/200000))
        y[,2] <- 2*(1 - y[,2])
        ks <- seq(credible,1,length=n.sim*(1-credible))
        lis <- t(apply(x,1,quantile,probs=ks-credible))
        lss <- t(apply(x,1,quantile,probs=ks))
        dif <- apply(abs(lss-lis),1,which.min)
        y[,3] <- lis[cbind(1:nrow(x),dif)]
        y[,4] <- lss[cbind(1:nrow(x),dif)]
        colnames(y) <- c("   Mean"," 2(1-PD) ","HDI_low","HDI_high")
        return(y)
  }
  if(object$regim > 1){
     thresholds <- matrix(resumen(matrix(object$chains$thresholds,nrow=object$regim-1))[,c(1,3,4)],ncol=3)
     out_$h <- mean(object$chains$h)
     out_$thresholds <- thresholds
     out_$threshold.series <- object$ts
  }
  out_$output.series <- ifelse(length(colnames(object$data[[1]]$y))==1,colnames(object$data[[1]]$y),paste(colnames(object$data[[1]]$y),collapse="    |    "))
  if(min(object$ars$q)>0) out_$exogenous.series <- ifelse(length(colnames(object$exogenous.series))==1,colnames(object$exogenous.series),paste(colnames(object$exogenous.series),collapse="    |    "))
  out_$dist <- object$dist
  out_$ssvs <- object$ssvs
  out_$location <- list()
  out_$scale <- list()
  out_$ars <- object$ars
  a <- ifelse(object$Intercept,"Intercept","")
  b <- ifelse(object$trend=="none","",paste0(ifelse(a=="","a ","+ a "),object$trend," time trend"))
  c <- ifelse(is.null(object$nseason),"",paste0("+ ",object$nseason," seasonal periods"))
  out_$deterministics <- paste(a,b,c)
  out_$sample.size <- nrow(object$data[[1]]$X)
  if(object$ssvs) out_$zeta <- list()
  for(i in 1:object$regim){
      out <- outs <- vector()
      for(j in 1:k){
          temp <- object$chains[[i]]$location[,seq(j,n.sim*k,k)]
          temps <- matrix(matrix(object$chains[[i]]$scale,k,n.sim*k)[,seq(j,n.sim*k,k)],nrow=k)
          if(j > 1){
             out <- cbind(out,matrix(NA,nrow(out),1),resumen(temp))
             outs <- cbind(outs,resumen(temps)[,c(1,3,4)])
          }else{
               out <- resumen(temp)
               outs <- resumen(temps)[,c(1,3,4)]
          }
      }
      outs <- matrix(outs,k,3*k)
      rownames(out) <- object$name[[i]]
      if(object$ssvs){
         temp <- apply(object$chains[[i]]$zeta,1,mean)
         out <- out[temp>0.5,]
      }
      outs <- matrix(cbind(outs,NA),k,3*k+1)
      outs <- outs[,c(seq(1,3*k,3),3*k+1,seq(2,3*k,3),3*k+1,seq(3,3*k,3))]
      outs <- matrix(outs,k,length(outs)/k)
      rownames(outs) <- colnames(object$data[[1]]$y)
      colnames(outs) <- c(rownames(outs),"",rownames(outs),"",rownames(outs))
      if(object$ssvs){
         quien <- object$deterministic + seq(k,object$ars$p[i]*k,k)
         namezeta <- paste0("OS.lag(",1:object$ars$p[i],")")
         if(object$ars$q[i]>0){
            quien <- c(quien,max(quien)+seq(object$r,object$ars$q[i]*object$r,object$r))
            namezeta <- c(namezeta,paste0("ES.lag(",1:object$ars$q[i],")"))
         }
         if(object$ars$d[i]>0){
            quien <- c(quien,max(quien)+seq(1,object$ars$d[i],1))
            namezeta <- c(namezeta,paste0("TS.lag(",1:object$ars$d[i],")"))
         }
         temp <- matrix(apply(matrix(object$chains[[i]]$zeta[quien,],length(quien),n.sim),1,mean),1,length(quien))
         colnames(temp) <- namezeta
         rownames(temp) <- "SSVS"
      }
      out_$location[[i]] <- out
      out_$scale[[i]] <- outs
      if(object$ssvs) out_$zeta[[i]] <- temp
  }
  if(object$dist %in% c("Skew-normal","Skew-Student-t")){
     out <- resumen(object$chains$delta)
     rownames(out) <- paste0(paste0("delta",1:k),paste0(rep("",max(nchar(object$name[[1]]))-6),collapse=" "))
     out_$delta <- out
  }
  if(object$dist %in% c("Slash","Contaminated normal","Student-t","Hyperbolic","Skew-Student-t")){
     out <- resumen(object$chains$extra)
     out[,2] <- NA
     if(object$dist %in% c("Slash","Student-t","Hyperbolic","Skew-Student-t")) rownames(out)[nrow(out)] <- paste0("nu",paste0(rep("",max(nchar(object$name[[1]]))-1),collapse=" "))
     else rownames(out)[nrow(out):(nrow(out)-1)] <- paste0(c("nu2","nu1"),paste0(rep("",max(nchar(object$name[[1]]))-2),collapse=" "))
     out_$extra <- out
  }
  if(!is.null(object$row.names)) out_$row.names <- object$row.names
  class(out_) <- "summary_mtar"
  return(out_)
}
#'
#'
#' @method print summary_mtar
#' @export
print.summary_mtar <- function(x, digits=max(3, getOption("digits") - 2),...){
  cat("\n\nSample size          :",paste0(x$sample.size," time points",ifelse(is.null(x$row.names),"",x$row.names)))
  cat(ifelse(x$ssvs,"\nOutput Series (OS)   :","\nOutput Series        :"),x$output.series)
  if(x$ars$nregim > 1) cat(ifelse(max(x$ars$d)>0,"\nThreshold Series (TS):","\nThreshold Series     :"),x$threshold.series)
  if(max(x$ars$q)>0) cat("\nExogenous Series (ES):",x$exogenous.series)
  cat("\nError Distribution   :",x$dist)
  cat("\nNumber of regimes    :",x$ars$nregim)
  cat("\nDeterministics       :",x$deterministics)
  if(min(x$ars$p)==max(x$ars$p)) cat("\nAutoregressive orders:",paste0(x$ars$p[1]," in each regime"))
  else cat("\nAutoregressive orders:",paste(x$ars$p,collapse=", "))
  if(max(x$ars$q)>0){
     if(min(x$ars$q)==max(x$ars$q)) cat("\nMaximum lags for ES  :",paste0(x$ars$q[1]," in each regime"))
     else cat("\nMaximum lags for ES  :",paste(x$ars$q,collapse=", "))
  }
  if(max(x$ars$d)>0){
     if(min(x$ars$d)==max(x$ars$d)) cat("\nMaximum lags for TS  :",paste0(x$ars$d[1]," in each regime"))
     else cat("\nMaximum lags for TS  :",paste(x$ars$d,collapse=", "))
  }
  cat("\n\n")
  if(x$ars$nregim > 1){
     thresholds <- round(x$thresholds,digits=digits)
     thresholds1 <- paste0(c("(-Inf",paste0("(",thresholds[,1])),",",c(paste0(thresholds[,1],"]"),"Inf)"))
     thresholds2 <- paste0(c("(-Inf",paste0("(",thresholds[,2])),",",c(paste0(thresholds[,2],"]"),"Inf)"))
     thresholds3 <- paste0(c("(-Inf",paste0("(",thresholds[,3])),",",c(paste0(thresholds[,3],"]"),"Inf)"))
     d <- data.frame(cbind(thresholds1,thresholds2,thresholds3))
     rownames(d) <- paste("Regime",1:nrow(d))
     colnames(d) <- rep(" ",3)
     cat("\nThresholds (Mean, HDI_low, HDI_high)\n")
     print(d)
  }
  for(i in 1:x$ars$nregim){
      cat("\n\nRegime",i,":\n")
      if(x$ssvs) print(round(x$zeta[[i]],digits=2),digits=2)
      cat("\nAutoregressive coefficients\n")
      print(round(x$location[[i]],digits=digits),na.print="   |   ")
      cat("\nScale parameter (Mean, HDI_low, HDI_high)\n")
      print(round(x$scale[[i]],digits=digits),na.print="   .")
  }
  if(x$dist %in% c("Skew-normal","Skew-Student-t")){
     cat("\n\nSkewness parameter","\n")
     print(round(x$delta,digits=digits),na.print="   .   ",)
  }
  if(x$dist %in% c("Slash","Contaminated normal","Student-t","Hyperbolic","Skew-Student-t")){
     cat("\n\nExtra parameter","\n")
     print(round(x$extra,digits=digits),na.print="   .   ")
  }
  cat("\n\n")
}
#'
#'
#' @method plot mtar
#' @export
plot.mtar <- function(x,...){
  plot(resid(x),...)
}
#'
#' @method fitted mtar
#' @export
fitted.mtar <- function(object,...){
  n.sim <- object$n.sim
  dist <- object$dist
  k <- ncol(object$data[[1]]$y)
  n <- nrow(object$data[[1]]$X)
  Mi <- idsi <- vector()
  if(object$dist=="Skew-Student-t")
     extra <- rowMeans(matrix(object$chains$extra,ncol=n.sim))
  if(object$dist %in% c("Skew-Student-t","Skew-normal"))
     delta <- rowMeans(matrix(object$chains$delta,ncol=n.sim))
  ids <- 1:n
  if(object$regim > 1){
     lims <- (object$ps+1):(length(object$threshold.series))
     h <- as.integer(round(mean(object$chains$h),digits=0))
     thresholds <- rowMeans(matrix(object$chains$thresholds,object$regim-1,ncol=n.sim))
     Z <- object$threshold.series[lims-h]
     regs <- cut(Z,breaks=c(-Inf,sort(thresholds),Inf),labels=FALSE)
  }else regs <- matrix(1,n,1)
  for(i in 1:object$regim){
      location <- matrix(0,nrow(object$chains[[i]]$location),k)
      for(j in 1:k) location[,j] <- rowMeans(matrix(object$chains[[i]]$location[,seq(j,n.sim*k,by=k)],nrow(location),n.sim))
      places <- regs==i
      y <- object$data[[i]]$y[places,]
      M <- object$data[[i]]$X[places,]%*%location
      switch(object$dist,
             "Skew-normal"={M  <-  M + sqrt(2/pi)*delta},
             "Skew-Student-t"={M  <-  M + sqrt(extra/pi)*(gamma((extra-1)/2)/gamma(extra/2))*delta})
      idsi <- c(idsi,ids[places])
      Mi <- rbind(Mi,M)
  }
  idsx <- sort(idsi,index=TRUE)$ix
  Mi <- matrix(Mi[idsx,],n,k)
  rownames(Mi) <- rownames(object$data[[1]]$y)
  colnames(Mi) <- colnames(object$data[[1]]$y)
  out <- list(observed=object$data[[1]]$y,fitted=Mi)
  if(object$log){
     out$observed <- exp(out$observed)
     out$fitted <- exp(out$fitted)
  }
  class(out) <- "fittedmtar"
  return(out)
}
#'
#' @method plot fittedmtar
#' @export
plot.fittedmtar <- function(x,...,last=NULL){
  last <- ifelse(is.null(last),nrow(x$observed),ceiling(abs(last)))
  nano_ <- list(...)
  nano_$x <- 1:last
  if(is.null(nano_$type)) nano_$type <- "p"
  if(is.null(nano_$pch)) nano_$pch <- 20
  if(is.null(nano_$lty)) nano_$lty <- 3
  if(is.null(nano_$col)) col <- "blue" else col <- nano_$col
  if(is.null(nano_$main)) nano_$ylab <- ""
  if(is.null(nano_$xlab)) nano_$xlab <- "Time"
  if(is.null(nano_$xaxt)) nano_$xaxt <- "n"
  for(j in 1:ncol(x$fitted)){
      nano_$y <- x$observed[1:last,j]
      nano_$main <- colnames(x$observed)[j]
      nano_$ylim <- range(cbind(x$observed[1:last,j],x$fitted[1:last,j]))
      nano_$col <- "black"
      dev.new()
      outm <- do.call("plot",nano_)
      lines(x$fitted[1:last,j],lty=nano_$lty,col=col)
  }
}
#' @method print listmtar
#' @export
print.listmtar <- function(x,...){
  x2 <- x[[1]]
  output.series <- ifelse(length(colnames(x2$data[[1]]$y))==1,colnames(x2$data[[1]]$y),paste(colnames(x2$data[[1]]$y),collapse="    |    "))
  if(min(x2$ars$q)>0) exogenous.series <- ifelse(length(colnames(x2$exogenous.series))==1,colnames(x2$exogenous.series),paste(colnames(x2$exogenous.series),collapse="    |    "))
  cat("\n\nSample size          :",paste0(nrow(x2$data[[1]]$X)," time points",ifelse(is.null(x2$row.names),"",x2$row.names)))
  cat("\nOutput Series        :",output.series)
  if(x2$ars$nregim > 1) cat(ifelse(max(x2$ars$d)>0,"\nThreshold Series (TS):","\nThreshold Series     :"),x2$ts)
  if(max(x2$ars$q)>0) cat("\nExogenous Series (ES):",exogenous.series)
  cat("\nError Distribution   :",paste0(x2$dist,collapse=", "))
  cat("\nNumber of regimes    :",paste0(c(x[[1]]$ars$nregim,x[[length(x)]]$ars$nregim),collapse=" to "))
  a <- ifelse(x2$Intercept,"Intercept","")
  b <- ifelse(x2$trend=="none","",paste0(ifelse(a=="","a ","+ a "),x2$trend," time trend"))
  c <- ifelse(is.null(x2$nseason),"",paste0("+ ",x2$nseason," seasonal periods"))
  cat("\nDeterministics       :",paste(a,b,c))
  cat("\nAutoregressive orders:",paste0(c(x[[1]]$ars$p[1],x[[length(x)]]$ars$p[1]),collapse=" to "))
  if(max(x2$ars$q)>0){
     cat("\nMaximum lags for ES  :",paste0(c(x[[1]]$ars$q[1],x[[length(x)]]$ars$q[1]),collapse=" to "))
  }
  if(max(x2$ars$d)>0){
     cat("\nMaximum lags for TS  :",paste0(c(x[[1]]$ars$d[1],x[[length(x)]]$ars$d[1]),collapse=" to "))
  }
}
#' @method print mtar
#' @export
print.mtar <- function(x,...){
    output.series <- ifelse(length(colnames(x$data[[1]]$y))==1,colnames(x$data[[1]]$y),paste(colnames(x$data[[1]]$y),collapse="    |    "))
    if(min(x$ars$q)>0) exogenous.series <- ifelse(length(colnames(x$exogenous.series))==1,colnames(x$exogenous.series),paste(colnames(x$exogenous.series),collapse="    |    "))
    cat("\n\nSample size          :",paste0(nrow(x$data[[1]]$X)," time points",ifelse(is.null(x$row.names),"",x$row.names)))
    cat("\nOutput Series        :",output.series)
    if(x$ars$nregim > 1) cat(ifelse(max(x$ars$d)>0,"\nThreshold Series (TS):","\nThreshold Series     :"),x$ts)
    if(max(x$ars$q)>0) cat("\nExogenous Series (ES):",exogenous.series)
    cat("\nError Distribution   :",x$dist)
    cat("\nNumber of regimes    :",x$regim)
    a <- ifelse(x$Intercept,"Intercept","")
    b <- ifelse(x$trend=="none","",paste0(ifelse(a=="","a ","+ a "),x$trend," time trend"))
    c <- ifelse(is.null(x$nseason),"",paste0("+ ",x$nseason," seasonal periods"))
    cat("\nDeterministics       :",paste(a,b,c))
    if(min(x$ars$p)==max(x$ars$p)) cat("\nAutoregressive orders:",paste0(x$ars$p[1]," in each regime"))
    else cat("\nAutoregressive orders:",paste(x$ars$p,collapse=", "))
    if(max(x$ars$q)>0){
       if(min(x$ars$q)==max(x$ars$q)) cat("\nMaximum lags for ES  :",paste0(x$ars$q[1]," in each regime"))
       else cat("\nMaximum lags for ES  :",paste(x$ars$q,collapse=", "))
    }
    if(max(x$ars$d)>0){
       if(min(x$ars$d)==max(x$ars$d)) cat("\nMaximum lags for TS  :",paste0(x$ars$d[1]," in each regime"))
       else cat("\nMaximum lags for TS  :",paste(x$ars$d,collapse=", "))
    }
}
#'
#' @method residuals mtar
#' @export
residuals.mtar <- function(object,...,type=c("quantile","mahalanobis")){
  type <- match.arg(type)
  n.sim <- object$n.sim
  dist <- object$dist
  if(dist %in% c("Skew-normal","Skew-Student-t"))
     stop("Models with Skew-normal or Skew-t as noise distribution are not supported!",call.=FALSE)
  k <- ncol(object$data[[1]]$y)
  idsi <- resi <- vector()
  if(object$dist %in% c("Student-t","Hyperbolic","Slash","Contaminated normal"))
     extra <- rowMeans(matrix(object$chains$extra,ncol=n.sim))
  ids <- 1:nrow(object$data[[1]]$X)
  if(object$regim > 1){
     lims <- (object$ps+1):(length(object$threshold.series))
     h <- as.integer(round(mean(object$chains$h),digits=0))
     thresholds <- rowMeans(matrix(object$chains$thresholds,object$regim-1,ncol=n.sim))
     Z <- object$threshold.series[lims-h]
     regs <- cut(Z,breaks=c(-Inf,sort(thresholds),Inf),labels=FALSE)
  }else regs <- matrix(1,nrow(object$data[[1]]$y),1)
  for(i in 1:object$regim){
      location <- matrix(0,nrow(object$chains[[i]]$location),k)
      scale <- matrix(0,k,k)
      for(j in 1:k){
          location[,j] <- rowMeans(matrix(object$chains[[i]]$location[,seq(j,n.sim*k,by=k)],nrow(location),n.sim))
          scale[,j] <- rowMeans(matrix(object$chains[[i]]$scale[,seq(j,n.sim*k,by=k)],k,n.sim))
      }
      places <- regs==i
      y <- object$data[[i]]$y[places,]
      X <- object$data[[i]]$X[places,]
      resu <- y-X%*%location
      ei <- eigen(scale,symmetric=TRUE)
      resu <- resu%*%(ei$vectors%*%diag(1/sqrt(as.vector(ei$values)))%*%t(ei$vectors))
      resi <- rbind(resi,resu)
      idsi <- c(idsi,ids[places])
  }
  resi <- matrix(resi,nrow(object$data[[1]]$X),k)
  TT <- 100000
  sim <- matrix(rnorm(TT*k),TT,k)
  u <- switch(dist,"Gaussian"={rep(1,TT)},
              "Student-t"={1/rgamma(TT,shape=extra/2,rate=extra/2)},
              "Slash"={1/rbeta(TT,shape1=extra/2,shape2=1)},
              "Contaminated normal"={1/(1 - (1-extra[2])*rbinom(TT,1,extra[1]))},
              "Hyperbolic"={rgig(n=TT,lambda=1,chi=1,psi=extra^2)},
              "Laplace"={rexp(TT,rate=1/8)})
  sim2 <- sort(rowSums(sim^2)*u)
  resi2 <- matrix(rowSums(resi^2),nrow(resi),1)
  resij <- resi2
  if(type=="quantile"){
     resi2 <- apply(resi2,1,function(x) mean(sim2<=x))
     resi3 <- ifelse(resi2>=0.5,1-resi2,resi2)
     resij <- qnorm(ifelse(.Machine$double.xmin>=resi3,.Machine$double.xmin,resi3))*ifelse(resi2>0.5,-1,1)
  }
  idsx <- sort(idsi,index=TRUE)$ix
  resij <- matrix(resij[idsx],length(resij),1)
  if(type=="quantile"){
     sim <- sim*matrix(sqrt(u),TT,k)
     for(i in 1:k){
         temp <- apply(matrix(resi[,i],nrow(resi),1),1,function(x) mean(sim[,i]<=x))
         temp2 <- ifelse(temp>=0.5,1-temp,temp)
         resi[,i] <- qnorm(ifelse(.Machine$double.xmin>=temp2,.Machine$double.xmin,temp2))*ifelse(temp>0.5,-1,1)
     }
  }
  resi <- matrix(resi[idsx,],nrow(resi),k)
  row.names(resij) <- row.names(resi) <- row.names(object$data[[1]]$y)
  colnames(resij) <- " "
  colnames(resi) <- colnames(object$data[[1]]$y)
  out_ <- list(full=resij,by.component=resi)
  class(out_) <- "residuals_mtar"
  return(out_)
}
#'
#' @method plot residuals_mtar
#' @export
plot.residuals_mtar <- function(x,...){
  nano_ <- list(...)
  if(is.null(nano_$pch)) nano_$pch <- 20
  if(is.null(nano_$ylim)) nano_$ylim <- range(x$full)
  if(is.null(nano_$col)) nano_$col <- "black"
  dev.new()
  par(mfrow=c(1,2))
  qqnorm(x$full,pch=nano_$pch,col=nano_$col,main="",ylim=nano_$ylim)
  abline(0,1,lty=3)
  x <- x$full
  hist(x,freq=FALSE,xlab="Quantile-type residual",ylab="Density",main="",xlim=nano_$ylim)
  curve(dnorm(x), col="blue", add=TRUE)
  #acf(x,main="",col=nano_$col)
  #pacf(x,main="",col=nano_$col)
}

#' @method print residuals_mtar
#' @export
print.residuals_mtar <- function(x, digits=max(3, getOption("digits") - 2), ...){
  x2 <- apply(cbind(x$full,x$by.component),2,quantile,probs=c(0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.95,0.99))
  colnames(x2) <- c("Full",colnames(x$by.component))
  rownames(x2) <- paste0("Quantile ",rownames(x2))
  print(x2,digits=digits,na.print="")
}
